default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL") { ENV.fetch("RAILS_MAX_THREADS") { 5 } } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  timeout: <%= ENV.fetch("DB_TIMEOUT", 5000) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "aidia_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "aidia_test") %>
  host: <%= ENV.fetch("POSTGRES_TEST_HOST", "localhost") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "aidia_production") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_CACHE_DB", "aidia_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_QUEUE_DB", "aidia_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_CABLE_DB", "aidia_production_cable") %>
    migrations_paths: db/cable_migrate
